#pragma once

#include <stdint.h>

/* Monospace font: printable ASCII then Latin-1 (0xA0-0xFF), 4-bit alpha, two pixels per byte
 * (high nibble first), rows top to bottom. Generated by tools/gen_font.py. */
#define FONT_MONO_W      10
#define FONT_MONO_H      20
#define FONT_MONO_GLYPHS (95 + 96)

extern const uint8_t font_mono_glyphs[FONT_MONO_GLYPHS][FONT_MONO_W * FONT_MONO_H / 2];
