#!/usr/bin/env python3
"""Generates main/font_mono.c: DejaVu Sans Mono rendered into 10x20 cells, 4-bit alpha.

Covers printable ASCII and Latin-1 (0xA0-0xFF), enough for French text and logs.
Needs Pillow: python3 -m pip install pillow
Usage: python3 tools/gen_font.py /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf > main/font_mono.c
"""
import sys

from PIL import Image, ImageDraw, ImageFont

CELL_W, CELL_H, SIZE = 10, 20, 16
CODES = list(range(0x20, 0x7F)) + list(range(0xA0, 0x100))


def glyph(font, ch):
    img = Image.new("L", (CELL_W, CELL_H), 0)
    ImageDraw.Draw(img).text((0, 0), ch, font=font, fill=255)
    px = [img.getpixel((x, y)) >> 4 for y in range(CELL_H) for x in range(CELL_W)]
    return [(px[i] << 4) | px[i + 1] for i in range(0, len(px), 2)]


def main():
    font = ImageFont.truetype(sys.argv[1], SIZE)
    print("/* Generated by tools/gen_font.py from DejaVu Sans Mono (Bitstream Vera license,")
    print(" * https://dejavu-fonts.github.io/License.html). Do not edit by hand. */")
    print('#include "font_mono.h"\n')
    print(f"const uint8_t font_mono_glyphs[FONT_MONO_GLYPHS][FONT_MONO_W * FONT_MONO_H / 2] = {{")
    for code in CODES:
        data = ", ".join(f"0x{b:02x}" for b in glyph(font, chr(code)))
        label = f"U+{code:04X}"
        print(f"    /* {label} */ {{{data}}},")
    print("};")


if __name__ == "__main__":
    main()
